export const SEED_WORDS_ES: [string, string][] = [
  ["hola","hello"],["adiós","goodbye"],["gracias","thank you"],["por favor","please"],
  ["sí","yes"],["no","no"],["buenos días","good morning"],["buenas noches","good night"],
  ["¿cómo estás?","how are you?"],["bien","good"],["mal","bad"],["agua","water"],
  ["comida","food"],["casa","house"],["perro","dog"],["gato","cat"],
  ["libro","book"],["tiempo","time"],["día","day"],["noche","night"],
  ["hombre","man"],["mujer","woman"],["niño","child"],["amigo","friend"],
  ["familia","family"],["madre","mother"],["padre","father"],["hermano","brother"],
  ["hermana","sister"],["hijo","son"],["hija","daughter"],["calle","street"],
  ["ciudad","city"],["país","country"],["escuela","school"],["trabajo","work"],
  ["dinero","money"],["tienda","store"],["restaurante","restaurant"],["hospital","hospital"],
  ["carro","car"],["grande","big"],["pequeño","small"],["bueno","good"],
  ["malo","bad"],["nuevo","new"],["viejo","old"],["bonito","pretty"],
  ["feo","ugly"],["rápido","fast"],["lento","slow"],["caliente","hot"],
  ["frío","cold"],["comer","to eat"],["beber","to drink"],["dormir","to sleep"],
  ["hablar","to speak"],["caminar","to walk"],["correr","to run"],["leer","to read"],
  ["escribir","to write"],["comprar","to buy"],["vender","to sell"],["abrir","to open"],
  ["cerrar","to close"],["uno","one"],["dos","two"],["tres","three"],
  ["cuatro","four"],["cinco","five"],["seis","six"],["siete","seven"],
  ["ocho","eight"],["nueve","nine"],["diez","ten"],["cien","one hundred"],
  ["rojo","red"],["azul","blue"],["verde","green"],["amarillo","yellow"],
  ["blanco","white"],["negro","black"],["hoy","today"],["mañana","tomorrow"],
  ["ayer","yesterday"],["siempre","always"],["nunca","never"],["aquí","here"],
  ["allí","there"],["arriba","up"],["abajo","down"],["izquierda","left"],
  ["derecha","right"],["comida","meal"],["desayuno","breakfast"],["almuerzo","lunch"],
  ["cena","dinner"],["pan","bread"],["leche","milk"],["carne","meat"],
  ["pollo","chicken"],["pescado","fish"],["arroz","rice"],["fruta","fruit"],
  ["verdura","vegetable"],["cerveza","beer"],["vino","wine"],["café","coffee"],
  ["té","tea"],["amor","love"],["corazón","heart"],["vida","life"],
  ["muerte","death"],["feliz","happy"],["triste","sad"],["enojado","angry"],
  ["cansado","tired"],["enfermo","sick"],["fuerte","strong"],["débil","weak"],
  ["importante","important"],["necesario","necessary"],["posible","possible"],["difícil","difficult"],
  ["fácil","easy"],["peligroso","dangerous"],["seguro","safe"],["lleno","full"],
  ["vacío","empty"],["rico","rich"],["pobre","poor"],["joven","young"],
  ["cabeza","head"],["mano","hand"],["pie","foot"],["ojo","eye"],
  ["boca","mouth"],["nariz","nose"],["oreja","ear"],["pelo","hair"],
  ["brazo","arm"],["pierna","leg"],["dedo","finger"],["espalda","back"],
  ["lluvia","rain"],["sol","sun"],["luna","moon"],["estrella","star"],
  ["mar","sea"],["montaña","mountain"],["río","river"],["árbol","tree"],
  ["flor","flower"],["cielo","sky"],["nube","cloud"],["viento","wind"],
  ["fuego","fire"],["tierra","earth"],["piedra","stone"],["playa","beach"],
  ["pensar","to think"],["saber","to know"],["poder","can/to be able"],["querer","to want"],
  ["tener","to have"],["ser","to be"],["estar","to be"],["ir","to go"],
  ["venir","to come"],["dar","to give"],["ver","to see"],["oír","to hear"],
  ["sentir","to feel"],["encontrar","to find"],["poner","to put"],["salir","to leave"],
  ["entrar","to enter"],["esperar","to wait"],["llamar","to call"],["preguntar","to ask"],
  ["responder","to answer"],["ayudar","to help"],["necesitar","to need"],["trabajar","to work"],
  ["vivir","to live"],["morir","to die"],["creer","to believe"],["jugar","to play"],
  ["cocinar","to cook"],["limpiar","to clean"],["lavar","to wash"],["vestir","to dress"],
  ["baño","bathroom"],["cocina","kitchen"],["dormitorio","bedroom"],["ventana","window"],
  ["puerta","door"],["mesa","table"],["silla","chair"],["cama","bed"],
  ["teléfono","phone"],["computadora","computer"],["televisión","television"],["música","music"],
  ["película","movie"],["fiesta","party"],["vacaciones","vacation"],["viaje","trip"],
  ["aeropuerto","airport"],["estación","station"],["hotel","hotel"],["mapa","map"],
  ["pasaporte","passport"],["equipaje","luggage"],["billete","ticket"],["precio","price"],
  ["barato","cheap"],["caro","expensive"],["gratis","free"],["abierto","open"],
  ["cerrado","closed"],["temprano","early"],["tarde","late"],["cerca","near"],
  ["lejos","far"],["derecho","straight"],["cruzar","to cross"],["esquina","corner"],
  ["semáforo","traffic light"],["puente","bridge"],["edificio","building"],["iglesia","church"],
  ["parque","park"],["museo","museum"],["biblioteca","library"],["mercado","market"],
  ["banco","bank"],["correo","post office"],["policía","police"],["bombero","firefighter"],
  ["médico","doctor"],["enfermero","nurse"],["abogado","lawyer"],["profesor","teacher"],
  ["estudiante","student"],["ingeniero","engineer"],["cocinero","cook"],["artista","artist"],
  ["cantante","singer"],["escritor","writer"],["periodista","journalist"],["conductor","driver"],
  ["rey","king"],["reina","queen"],["presidente","president"],["gobierno","government"],
  ["ley","law"],["paz","peace"],["guerra","war"],["libertad","freedom"],
  ["problema","problem"],["solución","solution"],["pregunta","question"],["respuesta","answer"],
  ["ejemplo","example"],["razón","reason"],["cambio","change"],["manera","way"],
];
