// [Thai script, romanized pronunciation, English]
export const SEED_WORDS_TH: [string, string, string][] = [
  // ── Greetings & Polite ─────────────────────────────
  ["สวัสดี", "sà-wàt-dee", "hello"],
  ["ขอบคุณ", "kòp-kun", "thank you"],
  ["ครับ", "kráp", "yes (male polite)"],
  ["ค่ะ", "kâ", "yes (female polite)"],
  ["ใช่", "châi", "yes"],
  ["ไม่ใช่", "mâi châi", "no"],
  ["ไม่", "mâi", "no / not"],
  ["สบายดี", "sà-baai-dee", "I'm fine"],
  ["ลาก่อน", "laa-gòn", "goodbye"],
  ["โชคดี", "chôhk-dee", "good luck"],
  ["ยินดี", "yin-dee", "you're welcome"],
  ["ขอโทษ", "kŏr-tôht", "sorry / excuse me"],
  ["ไม่เป็นไร", "mâi-bpen-rai", "no problem / never mind"],

  // ── Essential Phrases ──────────────────────────────
  ["ไม่เข้าใจ", "mâi-kâo-jai", "I don't understand"],
  ["เข้าใจ", "kâo-jai", "I understand"],
  ["พูดไทยไม่ได้", "pôot-tai-mâi-dâai", "I can't speak Thai"],
  ["พูดช้าๆ", "pôot-cháa-cháa", "speak slowly"],
  ["ช่วยด้วย", "chûay-dûay", "help me"],
  ["อะไร", "à-rai", "what"],
  ["ที่ไหน", "têe-nǎi", "where"],
  ["เมื่อไหร่", "mêua-rài", "when"],
  ["ทำไม", "tam-mai", "why"],
  ["อย่างไร", "yàang-rai", "how"],
  ["ใคร", "krai", "who"],
  ["นี่", "nêe", "this"],
  ["นั่น", "nân", "that"],

  // ── Numbers ────────────────────────────────────────
  ["หนึ่ง", "nèung", "one"],
  ["สอง", "sŏng", "two"],
  ["สาม", "sǎam", "three"],
  ["สี่", "sèe", "four"],
  ["ห้า", "hâa", "five"],
  ["หก", "hòk", "six"],
  ["เจ็ด", "jèt", "seven"],
  ["แปด", "bpàet", "eight"],
  ["เก้า", "gâo", "nine"],
  ["สิบ", "sìp", "ten"],
  ["ยี่สิบ", "yêe-sìp", "twenty"],
  ["ร้อย", "rói", "hundred"],
  ["พัน", "pan", "thousand"],

  // ── Food & Ordering ────────────────────────────────
  ["ข้าว", "kâao", "rice"],
  ["ไก่", "gài", "chicken"],
  ["หมู", "mŏo", "pork"],
  ["กุ้ง", "gûng", "shrimp"],
  ["ปลา", "bplaa", "fish"],
  ["ผัด", "pàt", "stir-fried"],
  ["ต้ม", "dtôm", "boiled / soup"],
  ["ทอด", "tôt", "fried"],
  ["ผัดไทย", "pàt-tai", "pad thai"],
  ["ต้มยำ", "dtôm-yam", "tom yum"],
  ["ส้มตำ", "sôm-dtam", "papaya salad"],
  ["ข้าวผัด", "kâao-pàt", "fried rice"],
  ["น้ำ", "nám", "water"],
  ["เบียร์", "bia", "beer"],
  ["กาแฟ", "gaa-fae", "coffee"],
  ["ชา", "chaa", "tea"],
  ["เผ็ด", "pèt", "spicy"],
  ["ไม่เผ็ด", "mâi-pèt", "not spicy"],
  ["หวาน", "wǎan", "sweet"],
  ["เปรี้ยว", "bprîao", "sour"],
  ["เค็ม", "kem", "salty"],
  ["อร่อย", "à-ròi", "delicious"],
  ["กิน", "gin", "eat"],
  ["ดื่ม", "dèum", "drink"],
  ["หิว", "hǐw", "hungry"],
  ["อิ่ม", "ìm", "full (not hungry)"],
  ["เช็คบิล", "chék-bin", "check please"],
  ["เอาอันนี้", "ao-an-née", "I want this one"],
  ["ไม่เอา", "mâi-ao", "I don't want"],
  ["เพิ่ม", "pêrm", "more / add"],
  ["ใส่ถุง", "sài-tŭng", "put in bag"],

  // ── Directions & Places ────────────────────────────
  ["ซ้าย", "sáai", "left"],
  ["ขวา", "kwǎa", "right"],
  ["ตรงไป", "dtrong-bpai", "go straight"],
  ["กลับ", "glàp", "go back / return"],
  ["ใกล้", "glâi", "near"],
  ["ไกล", "glai", "far"],
  ["ที่นี่", "têe-nêe", "here"],
  ["ที่นั่น", "têe-nân", "there"],
  ["ห้องน้ำ", "hông-nám", "bathroom"],
  ["โรงพยาบาล", "rohng-pá-yaa-baan", "hospital"],
  ["สถานีรถไฟฟ้า", "sà-tǎa-nee-rót-fai-fáa", "BTS station"],
  ["ตลาด", "dtà-làat", "market"],
  ["ร้านอาหาร", "ráan-aa-hǎan", "restaurant"],
  ["โรงแรม", "rohng-raem", "hotel"],
  ["ถนน", "tà-nŏn", "road / street"],
  ["ซอย", "soi", "alley / soi"],

  // ── Transport ──────────────────────────────────────
  ["ไป", "bpai", "go"],
  ["มา", "maa", "come"],
  ["แท็กซี่", "táek-sêe", "taxi"],
  ["รถเมล์", "rót-meh", "bus"],
  ["รถไฟฟ้า", "rót-fai-fáa", "BTS / skytrain"],
  ["เรือ", "reua", "boat"],
  ["มอเตอร์ไซค์", "mor-dtêr-sai", "motorcycle"],
  ["ไปที่...", "bpai-têe", "go to..."],
  ["จอดที่นี่", "jòt-têe-nêe", "stop here"],
  ["เท่าไหร่", "tâo-rài", "how much"],
  ["แพง", "paeng", "expensive"],
  ["ถูก", "tùuk", "cheap"],
  ["ลดได้ไหม", "lót-dâai-mǎi", "can you reduce the price"],
  ["ไกลไหม", "glai-mǎi", "is it far"],

  // ── Shopping & Money ───────────────────────────────
  ["เงิน", "ngern", "money"],
  ["ราคา", "raa-kaa", "price"],
  ["ซื้อ", "séu", "buy"],
  ["ขาย", "kǎai", "sell"],
  ["บาท", "bàat", "baht (currency)"],
  ["ใหญ่", "yài", "big"],
  ["เล็ก", "lék", "small"],
  ["สวย", "sǔay", "beautiful"],
  ["ดี", "dee", "good"],
  ["ไม่ดี", "mâi-dee", "not good / bad"],

  // ── Time ───────────────────────────────────────────
  ["วันนี้", "wan-née", "today"],
  ["พรุ่งนี้", "prûng-née", "tomorrow"],
  ["เมื่อวาน", "mêua-waan", "yesterday"],
  ["ตอนนี้", "dton-née", "now"],
  ["เช้า", "cháo", "morning"],
  ["เย็น", "yen", "evening"],
  ["กลางคืน", "glaang-keun", "night"],

  // ── People & Pronouns ──────────────────────────────
  ["ผม", "pŏm", "I (male)"],
  ["ฉัน", "chǎn", "I (female)"],
  ["คุณ", "kun", "you"],
  ["เขา", "kǎo", "he / she / they"],
  ["เรา", "rao", "we"],
  ["เพื่อน", "pêuan", "friend"],
  ["คนไทย", "kon-tai", "Thai person"],
  ["ฝรั่ง", "fà-ràng", "foreigner / westerner"],

  // ── Feelings & States ──────────────────────────────
  ["ร้อน", "rón", "hot"],
  ["เย็น", "yen", "cold / cool"],
  ["สนุก", "sà-nùk", "fun"],
  ["เหนื่อย", "nèuay", "tired"],
  ["ดีใจ", "dee-jai", "happy"],
  ["เสียใจ", "sǐa-jai", "sad"],
  ["รัก", "rák", "love"],
  ["ชอบ", "chôp", "like"],
  ["ไม่ชอบ", "mâi-chôp", "don't like"],
  ["กลัว", "glua", "afraid"],
];
